name: My-GitHub-basic

on:
  push:
    branches:
      - main

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello message
        run: echo "Hello, world!"

      - name: Show folders
        run: ls -l

      - name: Show terraform version
        run: terraform --version

      - name: Show Zip
        run: zip --version

  my-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Deploy
        run: echo "Hello, world from DEploy!"
